clone:
  path: github.com/triggity/gotestdrone2

build:
  image: golang
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go get
    - echo "michael foo"
    - go build
    - go test
  script:
    - go get
    - go test
